import { Creator } from './types'

export type Story = {
  id: string
  date: string
  day: string
  creator: Creator
  emoji: string
  concept: string
  overlayText: string
  prompt: string
  storyArc?: string
  higgsfieldJobId?: string
  generatedAt?: string
  status?: 'pending' | 'generated' | 'posted'
}

/**
 * STORY PROMPT STYLE (see docs/PROMPT_STYLE_GUIDE.md)
 *
 * Every story prompt must include:
 * 1. FACE LOCK: soul_2 with soul_id OR nano_banana_2 with <<<element>>>
 * 2. WARDROBE: specific garment, color, cut (deep-V REVEALING cleavage for bombshells, modest for Siya)
 * 3. HAIR + MAKEUP: state and style
 * 4. POSE + EXPRESSION: body position + gaze + facial expression
 * 5. SETTING: named venue + time of day
 * 6. LIGHTING: source + direction + quality
 * 7. REALISM: "Hyperrealistic 9:16, real skin pores, slight film grain, iPhone 17 Pro Max quality"
 * 8. BOLDNESS: BOLD SEXY (Kiara/Mia/Ava) or SWEET soft (Siya)
 *
 * SOUL IDs (locked, ready to use):
 *   Siya:  69db0f1c-ca4d-4238-aa59-9a23bfefb06d
 *   Kiara: 1e9f2dc4-1196-4778-83e3-5155b2fa432a
 *   Mia:   97625973-f756-4378-83d9-2336c2d26250
 *   Ava:   4e3cc9d3-4b86-4fc6-9b38-f4186fed4d7f
 */

// Daily Instagram Stories for each creator, July 2-29, 2026
// Format: 9:16 vertical, text overlay on image, casual snapshot-style
// Siya = normal Indian sweet-cute vibe. Kiara/Mia/Ava = bold/sexy/aspirational.
export const STORIES: Story[] = [
  // ============ SIYA (Bangalore, sweet Indian beauty) ============
  { id: 's-jul02', higgsfieldJobId: 'a4dfc4c8-b201-4f3d-b84b-ebeaf5e46c85', generatedAt: '2026-07-02', status: 'generated', date: '2026-07-02', day: 'Wed', creator: 'Siya', emoji: '☕', concept: 'Morning matcha in bed', overlayText: 'monday face 😌', prompt: 'Siya Sharma morning selfie in bed holding hot matcha latte, natural no-makeup dewy skin, cream silk pyjama top, soft window light Bangalore bedroom 9:16.' },
  { id: 's-jul03', date: '2026-07-03', day: 'Thu', creator: 'Siya', emoji: '✨', concept: 'Skincare shelf reveal', overlayText: 'the shelf that changed my skin 💫', prompt: 'Overhead phone shot of Siya\'s hand arranging luxury skincare on marble bathroom vanity, warm morning light 9:16.' },
  { id: 's-jul04', date: '2026-07-04', day: 'Fri', creator: 'Siya', emoji: '📚', concept: 'Café work in Indian block-print kurti', overlayText: 'friday deep work 💌', prompt: 'MODEL: soul_2 soul_id=69db0f1c-ca4d-4238-aa59-9a23bfefb06d. SETTING: Siya at Bangalore Third Wave Coffee Koramangala window seat 3pm. WARDROBE: Anokhi indigo block-print cotton kurti with tasteful V-neck + tiny Amrapali gold jhumkas + delicate gold chain + kohl liner. POSE: seated, hands on rose-gold MacBook, iced matcha in glass, soft focused expression looking down at laptop. LIGHTING: warm afternoon window light from left. 9:16 vertical story, hyperrealistic real skin pores film grain iPhone 17 Pro Max quality. SWEET soft Indian fashion — modest.' },
  { id: 's-jul05', date: '2026-07-05', day: 'Sat', creator: 'Siya', emoji: '💗', concept: 'Date night mirror', overlayText: 'getting ready 🥂', prompt: 'Siya at vanity mirror putting glossy nude lipstick, half-glam done, deep-V black silk top, ring light glow 9:16.' },
  { id: 's-jul06', date: '2026-07-06', day: 'Sun', creator: 'Siya', emoji: '🌾', concept: 'Family lunch spread', overlayText: 'sundays at amma\'s ✨', prompt: 'Overhead shot Siya\'s hand reaching for filter coffee at family table, brass thali with dosa, warm Indian home 9:16.' },
  { id: 's-jul07', date: '2026-07-07', day: 'Mon', creator: 'Siya', emoji: '💻', concept: 'Office desk in silk kurti + jhumkas', overlayText: 'she\'s at work again 💌', prompt: 'MODEL: soul_2 soul_id=69db0f1c-ca4d-4238-aa59-9a23bfefb06d. WARDROBE: soft peach silk kurti with delicate gold ari work + gold Amrapali jhumkas + delicate gold chain. SETTING: Siya at chic minimalist Bangalore home office desk 10am, rose-gold MacBook + Anokhi block-print planner + gold pen + iced matcha + peony in glass vase. POSE: hands on keyboard, soft focused smile, morning window light from left. 9:16 hyperrealistic real pores film grain. SWEET Indian modern-professional.' },
  { id: 's-jul08', date: '2026-07-08', day: 'Tue', creator: 'Siya', emoji: '☕', concept: 'Matcha refill café', overlayText: 'tuesday refill 🍵', prompt: 'Siya smiling holding iced matcha at café patio, cream knit top, soft glam 9:16.' },
  { id: 's-jul09', date: '2026-07-09', day: 'Wed', creator: 'Siya', emoji: '🌸', concept: 'Sunset walk selfie', overlayText: 'bangalore golden hour hits 🌸', prompt: 'Siya walking Cubbon Park sunset golden light selfie, cream cardigan, dewy skin 9:16.' },
  { id: 's-jul10', date: '2026-07-10', day: 'Thu', creator: 'Siya', emoji: '💄', concept: 'Beauty product close-up', overlayText: 'obsessed. review coming 🤍', prompt: 'Siya\'s hand holding new lipstick close to lips, soft focus dewy face partial view, ring light 9:16.' },
  { id: 's-jul11', date: '2026-07-11', day: 'Fri', creator: 'Siya', emoji: '💅', concept: 'GRWM soft-glam', overlayText: 'friday face 💅', prompt: 'Siya vanity mirror applying blush with brush, half glam, cream silk cami, ring light 9:16.' },
  { id: 's-jul12', date: '2026-07-12', day: 'Sat', creator: 'Siya', emoji: '🍛', concept: 'Family thali platter', overlayText: 'amma\'s hands 🌾', prompt: 'Overhead brass thali plate south Indian food, Siya\'s hand reaching for banana leaf, warm home light 9:16.' },
  { id: 's-jul13', date: '2026-07-13', day: 'Sun', creator: 'Siya', emoji: '🛁', concept: 'Sunday spa self-care', overlayText: 'sunday reset 🛁', prompt: 'Siya face mask selfie, silk hair wrap, cream robe collar, warm bathroom light 9:16.' },
  { id: 's-jul14', date: '2026-07-14', day: 'Mon', creator: 'Siya', emoji: '✨', concept: 'Monday office vanity', overlayText: 'softness is power 🤍', prompt: 'Siya at home office desk deep-V cream ribbed top, coffee, laptop, morning light 9:16.' },
  { id: 's-jul15', date: '2026-07-15', day: 'Tue', creator: 'Siya', emoji: '📖', concept: 'Reading with tea', overlayText: 'quiet tuesday 📖', prompt: 'Siya reading book at couch, tea cup, silk pyjama, cozy Bangalore evening light 9:16.' },
  { id: 's-jul16', date: '2026-07-16', day: 'Wed', creator: 'Siya', emoji: '✈️', concept: 'DXB airport arrival', overlayText: 'landed 🌴', prompt: 'Siya at DXB airport arrival hall with cream travel outfit designer tote deep-V cream cardigan soft glam 9:16.', storyArc: 'dubai' },
  { id: 's-jul17', date: '2026-07-17', day: 'Thu', creator: 'Siya', emoji: '💆', concept: 'Dubai spa selfie', overlayText: 'spa girl behavior 🤍', prompt: 'Siya at Dubai luxury spa white robe face mask on dewy skin gold necklace warm spa lighting 9:16.', storyArc: 'dubai' },
  { id: 's-jul18', date: '2026-07-18', day: 'Fri', creator: 'Siya', emoji: '🛍️', concept: 'Dubai Mall haul', overlayText: 'DXB mall was WILD 🛍️', prompt: 'Siya at Dubai Mall shopping bags in hand selfie, deep-V pink silk top, warm mall light 9:16.', storyArc: 'dubai' },
  { id: 's-jul19', date: '2026-07-19', day: 'Sat', creator: 'Siya', emoji: '🥂', concept: 'Yacht drinks with girls', overlayText: 'never leaving 🛥️', prompt: 'Siya at Dubai yacht deck with champagne flute, cream flowy sarong set showing collarbones, sunny Palm Jumeirah backdrop 9:16.', storyArc: 'dubai' },
  { id: 's-jul20', date: '2026-07-20', day: 'Sun', creator: 'Siya', emoji: '🥂', concept: 'Dubai brunch selfie', overlayText: 'hungover but happy 🍾', prompt: 'Siya + friends at Dubai brunch table oversized sunglasses mimosa hungover style laughing candid 9:16.', storyArc: 'dubai' },
  { id: 's-jul21', date: '2026-07-21', day: 'Mon', creator: 'Siya', emoji: '💔', concept: 'Airport goodbye tears', overlayText: 'crying at boarding 😭', prompt: 'Siya at DXB airport emotional goodbye hug with a friend, cream travel outfit, tears in eyes soft light 9:16.', storyArc: 'dubai' },
  { id: 's-jul22', date: '2026-07-22', day: 'Tue', creator: 'Siya', emoji: '🛍️', concept: 'Dubai loot unboxing', overlayText: 'the haul 🛍️', prompt: 'Overhead flatlay of Siya\'s Dubai purchases on bed — perfume boxes gold jewelry beauty products cream silk 9:16.' },
  { id: 's-jul23', date: '2026-07-23', day: 'Wed', creator: 'Siya', emoji: '☕', concept: 'Back to Bangalore coffee', overlayText: 'home sweet home 🏠', prompt: 'Siya home in cream silk robe holding coffee mug soft warm morning window light 9:16.' },
  { id: 's-jul24', date: '2026-07-24', day: 'Thu', creator: 'Siya', emoji: '👗', concept: 'Date night outfit reveal', overlayText: 'tonight\'s fit 💗', prompt: 'Siya mirror selfie in blush pink modest cocktail dress with tasteful collarbones, soft glam, bedroom mirror 9:16.' },
  { id: 's-jul25', date: '2026-07-25', day: 'Fri', creator: 'Siya', emoji: '🍰', concept: 'Weekend café dessert', overlayText: 'friday sweet tooth 🍰', prompt: 'Siya at chic café patio holding fork of tiramisu, cream knit top, dewy skin, warm light 9:16.' },
  { id: 's-jul26', date: '2026-07-26', day: 'Sat', creator: 'Siya', emoji: '💄', concept: 'GRWM night out', overlayText: 'ready 💄', prompt: 'Siya at vanity finished glam evening look deep-V black silk halter, soft ring light 9:16.' },
  { id: 's-jul27', date: '2026-07-27', day: 'Sun', creator: 'Siya', emoji: '🛁', concept: 'Sunday spa gua sha', overlayText: 'face massage sunday 🛁', prompt: 'Siya doing gua sha at vanity mirror silk hair wrap dewy skin, cream pyjama, warm morning light 9:16.' },
  { id: 's-jul28', date: '2026-07-28', day: 'Mon', creator: 'Siya', emoji: '🌸', concept: 'Monday morning ritual', overlayText: 'the routine 🌸', prompt: 'Overhead flatlay of Siya\'s hand holding skincare bottle at vanity morning routine, marble surface 9:16.' },
  { id: 's-jul29', date: '2026-07-29', day: 'Tue', creator: 'Siya', emoji: '👋', concept: 'Café goodbye wave', overlayText: 'ily see you tomorrow 🤍', prompt: 'Siya at café patio waving goodbye to camera cream knit top warm sunset light 9:16.' },

  // ============ KIARA (Mumbai fitness/beauty, BOLD SEXY) ============
  { id: 'k-jul02', higgsfieldJobId: '5e953cd2-9e4f-47bf-bb5d-e4f91f36d9de', generatedAt: '2026-07-02', status: 'generated', date: '2026-07-02', day: 'Wed', creator: 'Kiara', emoji: '💪', concept: 'Gym mirror check', overlayText: 'form check 💪', prompt: 'Kiara Cult.fit gym mirror selfie plunging deep-V black sports bra revealing cleavage toned abs sleek high ponytail moody red neon 9:16.' },
  { id: 'k-jul03', date: '2026-07-03', day: 'Thu', creator: 'Kiara', emoji: '🥤', concept: 'Protein shake sultry', overlayText: 'gainz 🔥', prompt: 'Kiara close-up sipping protein shake from black shaker bottle sultry gaze deep-V black crop showing revealing cleavage, gym backdrop 9:16.' },
  { id: 'k-jul04', date: '2026-07-04', day: 'Fri', creator: 'Kiara', emoji: '🐕', concept: 'Blinki cuddle', overlayText: 'my whole heart 🐶', prompt: 'Kiara on couch cuddling Blinki (tri-color beagle pink collar element) close to face, deep-V oversized cream sweater slipping off shoulder, cozy 9:16.' },
  { id: 'k-jul05', date: '2026-07-05', day: 'Sat', creator: 'Kiara', emoji: '🏋️', concept: 'Deadlift PR sultry', overlayText: 'new PR 🔥 80kg', prompt: 'Kiara mid-deadlift Cult.fit gym intense focused, plunging deep-V black sports bra revealing cleavage + leggings, sweaty glow 9:16.' },
  { id: 'k-jul06', date: '2026-07-06', day: 'Sun', creator: 'Kiara', emoji: '🌅', concept: 'Balcony sunset with wine', overlayText: 'sunday softness 🍷', prompt: 'Kiara on Mumbai balcony deep-V black silk slip revealing cleavage holding wine glass Blinki beside her golden sunset skyline behind 9:16.' },
  { id: 'k-jul07', date: '2026-07-07', day: 'Mon', creator: 'Kiara', emoji: '🔥', concept: 'Monday car reveal — Mini Cooper Countryman', overlayText: 'monday, meet baby 🍏💚', prompt: 'MODEL: nano_banana_2 (need to lock car). CHARACTER FACE LOCK: <<<62e48caf-931d-45a0-a2a7-b4a57c63ba0b>>> (Kiara Rai Reference Element). CAR: British Racing Green Mini Cooper Countryman JCW 2024 (dark green metallic body + white roof + white bonnet stripes running from grille to windshield + black JCW-style alloys + black window trim + Union Jack side mirrors), Maharashtra vanity plate "MH 04 KR 2024" clearly visible on front bumper, parked slightly angled on a chic Pali Naka Bandra Mumbai side-street with palm trees + bougainvillea + Portuguese-style bungalows blurred behind. WARDROBE: Kiara wearing plunging deep-V black bodycon ribbed knit crop top REVEALING tasteful cleavage + high-waisted cream tailored wide-leg trousers + black square-toe pointed heels + gold layered necklaces + tiny gold hoops + oversized black Celine cat-eye sunglasses pushed up on her head. HAIR: bombshell dark brown wavy hair mid-back cascading over both shoulders, slight movement from breeze. MAKEUP: sultry glam — bronze smoky eye, glossy nude-pink lip, subtle contour, dewy skin. POSE: leaning back against the driver-side door of the Mini, one leg crossed over the other, right elbow on the roof, keys hanging from her right hand, chin tilted slightly up, sultry confident direct gaze at camera with soft closed-mouth smirk. FACE MARKER: tiny mole above right upper lip (identity lock). LIGHTING: warm cinematic Mumbai morning sun 8am from her left creating dimensional shadow on car body and skin. CINEMATOGRAPHY: 9:16 story vertical, phone at chest height capturing full car + Kiara + plate. TEXT OVERLAY: "monday, meet baby 🍏💚" hand-drawn Instagram Story text placed top-third with white bold. Hyperrealistic Instagram Story 9:16, real skin pores + subtle car paint reflections, slight film grain, iPhone 17 Pro Max quality. BOLD SEXY confident bombshell. No CGI, no plastic skin. Lock car face and plate for reuse.' },
  { id: 'k-jul08', date: '2026-07-08', day: 'Tue', creator: 'Kiara', emoji: '💪', concept: 'Gym progress selfie', overlayText: 'progress hits 💪', prompt: 'Kiara Cult.fit locker room mirror selfie showing toned abs, deep-V black sports bra revealing cleavage, sultry smirk 9:16.' },
  { id: 'k-jul09', date: '2026-07-09', day: 'Wed', creator: 'Kiara', emoji: '🏃‍♀️', concept: 'Cardio run outdoor', overlayText: 'hate cardio btw 🥲', prompt: 'Kiara at Mumbai promenade run mid-stride deep-V sports set revealing cleavage bombshell ponytail flying golden hour 9:16.' },
  { id: 'k-jul10', date: '2026-07-10', day: 'Thu', creator: 'Kiara', emoji: '🥗', concept: 'Meal prep flatlay', overlayText: 'high protein plate 🍗', prompt: 'Overhead of Kiara\'s hand holding fork over grilled chicken quinoa salad in glass container marble kitchen 9:16.' },
  { id: 'k-jul11', date: '2026-07-11', day: 'Fri', creator: 'Kiara', emoji: '☕', concept: 'Rohan making tea', overlayText: 'he\'s so cute 🥹', prompt: 'Kiara POV shot of Rohan (boyfriend face lock Punjabi Indian man muscular tee) at kitchen counter making chai, Mumbai apartment morning light 9:16.' },
  { id: 'k-jul12', date: '2026-07-12', day: 'Sat', creator: 'Kiara', emoji: '🌾', concept: 'Punjab family kitchen', overlayText: 'mom is cooking 🌾', prompt: 'Kiara + her mom Simran (Punjabi mom face lock salwar-kameez) in Punjab family kitchen, warm sunlight 9:16.' },
  { id: 'k-jul13', date: '2026-07-13', day: 'Sun', creator: 'Kiara', emoji: '😴', concept: 'Lazy Sunday couch', overlayText: 'rest day fr 😴', prompt: 'Kiara lazy on Mumbai apartment couch oversized white tee slipping off shoulder Blinki on her lap warm afternoon 9:16.' },
  { id: 'k-jul14', date: '2026-07-14', day: 'Mon', creator: 'Kiara', emoji: '💗', concept: 'Rohan date rooftop', overlayText: 'monday spoiled 🖤', prompt: 'Kiara + Rohan (boyfriend face lock) at Mumbai rooftop bar Kiara in deep-V black satin midi revealing cleavage he in fitted black tee, sultry couple selfie 9:16.' },
  { id: 'k-jul15', date: '2026-07-15', day: 'Tue', creator: 'Kiara', emoji: '✈️', concept: 'Packing for Dubai', overlayText: 'DXB in 24h 🌴', prompt: 'Overhead Kiara\'s Mumbai bedroom folding bikinis and silk dresses into open Louis Vuitton suitcase 9:16.', storyArc: 'dubai' },
  { id: 'k-jul16', date: '2026-07-16', day: 'Wed', creator: 'Kiara', emoji: '🌴', concept: 'Dubai suite reveal', overlayText: 'room 4207 🌴', prompt: 'Kiara Dubai luxury hotel suite balcony sunrise Burj Khalifa view deep-V silk robe revealing cleavage bombshell hair 9:16.', storyArc: 'dubai' },
  { id: 'k-jul17', date: '2026-07-17', day: 'Thu', creator: 'Kiara', emoji: '🥂', concept: 'Nobu with the girls', overlayText: 'nobu >>> 🥂', prompt: 'Kiara + all 4 friends (Soul V2 all locked) at Nobu Dubai table champagne toast candid laughing 9:16.', storyArc: 'dubai' },
  { id: 'k-jul18', date: '2026-07-18', day: 'Fri', creator: 'Kiara', emoji: '🌆', concept: 'Dubai skyline pose', overlayText: 'dubai does something to me ✨', prompt: 'Kiara on Dubai balcony sunset deep-V white silk crochet crop revealing cleavage bombshell hair Palm Jumeirah golden hour 9:16.', storyArc: 'dubai' },
  { id: 'k-jul19', date: '2026-07-19', day: 'Sat', creator: 'Kiara', emoji: '👙', concept: 'Yacht bikini sultry', overlayText: 'yacht life 🍾🛥️', prompt: 'Kiara Dubai Marina yacht plunging deep-V black bikini top revealing cleavage + gold body chain bombshell wet hair Palm Jumeirah 9:16.', storyArc: 'dubai' },
  { id: 'k-jul20', date: '2026-07-20', day: 'Sun', creator: 'Kiara', emoji: '🥂', concept: 'Dubai brunch group', overlayText: 'brunch cures all 🥂', prompt: 'Kiara + 4 friends Soul V2 Dubai luxury brunch mimosas oversized sunglasses hungover glam candid 9:16.', storyArc: 'dubai' },
  { id: 'k-jul21', date: '2026-07-21', day: 'Mon', creator: 'Kiara', emoji: '💔', concept: 'DXB airport goodbye', overlayText: 'crying rn 😭', prompt: 'Kiara at DXB emotional hug with Ava (Soul V2) cream travel outfit deep-V 9:16.', storyArc: 'dubai' },
  { id: 'k-jul22', date: '2026-07-22', day: 'Tue', creator: 'Kiara', emoji: '🐕', concept: 'Blinki reunion', overlayText: 'blinki missed me 🥹', prompt: 'Kiara kneeling reunion with Blinki (element lock) Blinki jumping into arms joyful genuine laugh Mumbai apartment 9:16.' },
  { id: 'k-jul23', date: '2026-07-23', day: 'Wed', creator: 'Kiara', emoji: '🌴', concept: 'Goa bound in Mini', overlayText: 'goa in 24h 🌴💚', prompt: 'Kiara standing beside green Mini Cooper Countryman MH 04 KR 2024 with packed roof rack, deep-V black crop revealing cleavage + palazzo, Mumbai driveway 9:16.', storyArc: 'goa' },
  { id: 'k-jul24', date: '2026-07-24', day: 'Thu', creator: 'Kiara', emoji: '👙', concept: 'Goa beach bikini', overlayText: 'sun sea sand 🌴', prompt: 'Kiara Anjuna beach Goa plunging deep-V black triangle bikini revealing cleavage + high-cut bottoms + gold body chain sultry sunset 9:16.', storyArc: 'goa' },
  { id: 'k-jul25', date: '2026-07-25', day: 'Fri', creator: 'Kiara', emoji: '🍹', concept: 'Goa beach club', overlayText: 'sundowners 🌅', prompt: 'Kiara at Goa beach club daybed white crochet bikini + sheer sarong wrap gold body chain coconut cocktail 9:16.', storyArc: 'goa' },
  { id: 'k-jul26', date: '2026-07-26', day: 'Sat', creator: 'Kiara', emoji: '🌅', concept: 'Goa sunset with Rohan', overlayText: 'him 🖤', prompt: 'Kiara + Rohan (boyfriend lock) walking Goa beach sunset holding hands both in swimwear silhouette golden sky 9:16.', storyArc: 'goa' },
  { id: 'k-jul27', date: '2026-07-27', day: 'Sun', creator: 'Kiara', emoji: '🔙', concept: 'Back in Mumbai', overlayText: 'back to reality 🔙', prompt: 'Kiara on Mumbai balcony sunrise coffee deep-V cream cami sun-kissed tan glow 9:16.' },
  { id: 'k-jul28', date: '2026-07-28', day: 'Mon', creator: 'Kiara', emoji: '💼', concept: 'Monday power dress', overlayText: 'monday face 💼', prompt: 'Kiara Mumbai office elevator mirror selfie deep-V white blazer over black satin cami revealing cleavage + trousers bombshell hair 9:16.' },
  { id: 'k-jul29', date: '2026-07-29', day: 'Tue', creator: 'Kiara', emoji: '💪', concept: 'Gym reset selfie', overlayText: 'back at it 💪', prompt: 'Kiara Cult.fit gym mirror deep-V black sports bra revealing cleavage sleek ponytail sultry direct gaze 9:16.' },

  // ============ MIA (Chicago fitness, BOLD SEXY) ============
  { id: 'm-jul02', higgsfieldJobId: 'd6f7ffce-5619-4488-a3b9-1f43c720f677', generatedAt: '2026-07-02', status: 'generated', date: '2026-07-02', day: 'Wed', creator: 'Mia', emoji: '🌅', concept: 'Sunrise run POV', overlayText: '5:47am 🌅', prompt: 'Mia mid-stride sunrise Chicago Lake Michigan trail POV deep-V white sports bra revealing cleavage + shorts bombshell blonde ponytail 9:16.' },
  { id: 'm-jul03', date: '2026-07-03', day: 'Thu', creator: 'Mia', emoji: '🥗', concept: 'Meal prep sunday', overlayText: 'girl dinner but healthy 🥗', prompt: 'Overhead marble Chicago kitchen Mia\'s hand arranging grilled chicken quinoa protein bowl 9:16.' },
  { id: 'm-jul04', date: '2026-07-04', day: 'Fri', creator: 'Mia', emoji: '🇺🇸', concept: '4th of July fit', overlayText: 'happy 4th 🇺🇸🎇', prompt: 'Mia in deep-V red bikini top revealing cleavage + white shorts American flag backdrop Chicago rooftop 9:16.' },
  { id: 'm-jul05', date: '2026-07-05', day: 'Sat', creator: 'Mia', emoji: '💪', concept: 'Saturday gym pump', overlayText: 'pump city 💪', prompt: 'Mia Chicago high-rise gym floor-to-ceiling window mid-workout deep-V white sports bra revealing cleavage bombshell ponytail 9:16.' },
  { id: 'm-jul06', date: '2026-07-06', day: 'Sun', creator: 'Mia', emoji: '🥕', concept: 'Sunday farmers market', overlayText: 'sunday market 🥕', prompt: 'Mia at Chicago farmers market holding fresh produce tote deep-V crop showing tasteful cleavage + high-waist bike shorts 9:16.' },
  { id: 'm-jul07', date: '2026-07-07', day: 'Mon', creator: 'Mia', emoji: '🏃‍♀️', concept: 'Grant Park run', overlayText: 'monday city belongs to me 🌇', prompt: 'Mia mid-stride Grant Park run Chicago skyline behind sun-kissed blonde ponytail deep-V white sports bra 9:16.' },
  { id: 'm-jul08', date: '2026-07-08', day: 'Tue', creator: 'Mia', emoji: '💪', concept: 'Blake gym partner', overlayText: 'gym daddy 🖤', prompt: 'Mia + Blake (boyfriend lock American ripped man) at Chicago gym Mia in deep-V neon sports bra + shorts he in fitted tank both mid-workout 9:16.' },
  { id: 'm-jul09', date: '2026-07-09', day: 'Wed', creator: 'Mia', emoji: '🏙️', concept: 'Chicago skyline view', overlayText: 'my city 🏙️', prompt: 'Mia rooftop Chicago skyline view sun-kissed deep-V white slip dress revealing cleavage bombshell hair 9:16.' },
  { id: 'm-jul10', date: '2026-07-10', day: 'Thu', creator: 'Mia', emoji: '🌾', concept: 'Farmers market tote', overlayText: 'meal prep loading 🥕', prompt: 'Mia at Chicago Green City Market holding basket of fresh vegetables deep-V white crop + athleisure joggers 9:16.' },
  { id: 'm-jul11', date: '2026-07-11', day: 'Fri', creator: 'Mia', emoji: '🍸', concept: 'Rooftop cocktail Friday', overlayText: 'earned it 🍸', prompt: 'Mia Chicago rooftop bar deep-V black satin slip dress revealing cleavage bombshell hair cocktail city skyline 9:16.' },
  { id: 'm-jul12', date: '2026-07-12', day: 'Sat', creator: 'Mia', emoji: '🍝', concept: 'Family dinner + Blake', overlayText: 'family + him 🤎', prompt: 'Mia + Blake at Chicago suburban family dinner deep-V cream sundress revealing cleavage Blake\'s arm around her chair mom dad brother sister at table 9:16.' },
  { id: 'm-jul13', date: '2026-07-13', day: 'Sun', creator: 'Mia', emoji: '🥕', concept: 'Sunday reset', overlayText: 'sunday reset 🥕', prompt: 'Mia at Chicago apartment kitchen sunday morning prep deep-V fitted crop tank showing tasteful cleavage + bike shorts 9:16.' },
  { id: 'm-jul14', date: '2026-07-14', day: 'Mon', creator: 'Mia', emoji: '💗', concept: 'Date night Blake', overlayText: 'monday but soft 🖤', prompt: 'Mia + Blake (boyfriend lock) Chicago upscale restaurant Mia deep-V little black dress revealing cleavage he in fitted button-down candid moment 9:16.' },
  { id: 'm-jul15', date: '2026-07-15', day: 'Tue', creator: 'Mia', emoji: '🎒', concept: 'Airport bag pack', overlayText: 'dubai loading 🌴', prompt: 'Overhead Mia\'s Chicago apartment bed with bikinis athleisure open Louis Vuitton suitcase 9:16.', storyArc: 'dubai' },
  { id: 'm-jul16', date: '2026-07-16', day: 'Wed', creator: 'Mia', emoji: '🌴', concept: 'Dubai suite window', overlayText: 'we\'re here 🌴', prompt: 'Mia Dubai luxury hotel window shot Burj Khalifa view deep-V white silk robe revealing cleavage bombshell blonde 9:16.', storyArc: 'dubai' },
  { id: 'm-jul17', date: '2026-07-17', day: 'Thu', creator: 'Mia', emoji: '🐪', concept: 'Desert safari sunset', overlayText: 'dune girl 🌅', prompt: 'Mia Dubai desert sunset dune deep-V white boho bikini top revealing cleavage + sarong bombshell blonde hair in wind 9:16.', storyArc: 'dubai' },
  { id: 'm-jul18', date: '2026-07-18', day: 'Fri', creator: 'Mia', emoji: '💪', concept: 'Dubai hotel gym', overlayText: 'still training 💪', prompt: 'Mia Dubai luxury hotel gym Palm Jumeirah window deep-V neon green sports bra revealing cleavage + shorts 9:16.', storyArc: 'dubai' },
  { id: 'm-jul19', date: '2026-07-19', day: 'Sat', creator: 'Mia', emoji: '🛥️', concept: 'Yacht sunset bikini', overlayText: 'yacht mode 🛥️🍾', prompt: 'Mia yacht Dubai Marina deep-V neon bikini top revealing cleavage + gold body chain bombshell wet hair champagne golden sunset 9:16.', storyArc: 'dubai' },
  { id: 'm-jul20', date: '2026-07-20', day: 'Sun', creator: 'Mia', emoji: '🎉', concept: 'Dubai club night', overlayText: 'we blacked out 💫', prompt: 'Mia at Dubai White club dance floor deep-V short mini dress revealing cleavage neon lights bombshell hair 9:16.', storyArc: 'dubai' },
  { id: 'm-jul21', date: '2026-07-21', day: 'Mon', creator: 'Mia', emoji: '💔', concept: 'Airport polaroid', overlayText: 'til next time 💔', prompt: 'Mia at DXB airport polaroid group photo of 4 girls emotional smile cream lounge deep-V 9:16.', storyArc: 'dubai' },
  { id: 'm-jul22', date: '2026-07-22', day: 'Tue', creator: 'Mia', emoji: '☕', concept: 'Chicago morning post-trip', overlayText: 'back home ☕', prompt: 'Mia Chicago apartment window morning post-Dubai sun-kissed tan deep-V white lounge revealing cleavage coffee 9:16.' },
  { id: 'm-jul23', date: '2026-07-23', day: 'Wed', creator: 'Mia', emoji: '💪', concept: 'Back to gym', overlayText: 'REVENGE workout 💪', prompt: 'Mia Chicago high-rise gym mid-set weighted lunges deep-V white sports bra revealing cleavage bombshell ponytail 9:16.' },
  { id: 'm-jul24', date: '2026-07-24', day: 'Thu', creator: 'Mia', emoji: '📱', concept: 'Program prep', overlayText: 'building something 👀', prompt: 'Mia at Chicago apartment desk MacBook + notebook + iced coffee planning deep-V cream oversized sweater falling off shoulder 9:16.' },
  { id: 'm-jul25', date: '2026-07-25', day: 'Fri', creator: 'Mia', emoji: '🚙', concept: 'Miami road trip Hummer', overlayText: 'miami bound 🌊', prompt: 'Mia beside her massive black Hummer EV SUV Illinois plate MCARTER parked at highway rest stop, deep-V white crop revealing cleavage + denim shorts bombshell hair sunglasses 9:16.', storyArc: 'miami' },
  { id: 'm-jul26', date: '2026-07-26', day: 'Sat', creator: 'Mia', emoji: '👙', concept: 'Miami beach bikini', overlayText: 'miami is HOT 🔥', prompt: 'Mia Miami South Beach plunging deep-V neon green triangle bikini revealing cleavage + high-cut bottoms gold body chain bombshell wet blonde hair 9:16.', storyArc: 'miami' },
  { id: 'm-jul27', date: '2026-07-27', day: 'Sun', creator: 'Mia', emoji: '🌅', concept: 'Miami sunset rooftop', overlayText: 'never leaving 🌅', prompt: 'Mia Miami hotel rooftop deep-V white silk slip dress revealing cleavage cocktail bombshell hair Miami sunset 9:16.', storyArc: 'miami' },
  { id: 'm-jul28', date: '2026-07-28', day: 'Mon', creator: 'Mia', emoji: '🏙️', concept: 'Back Chicago Monday', overlayText: 'my city 🏙️', prompt: 'Mia Chicago apartment window Monday morning deep-V white lounge revealing cleavage sun-kissed tan coffee 9:16.' },
  { id: 'm-jul29', date: '2026-07-29', day: 'Tue', creator: 'Mia', emoji: '🚀', concept: 'Launch day motivation', overlayText: 'IT\'S LIVE 🚀', prompt: 'Mia Chicago studio bold selfie deep-V white sports bra revealing cleavage + leggings holding phone showing program screen 9:16.' },

  // ============ AVA (NYC fashion/beauty, BOLD SEXY) ============
  { id: 'a-jul02', higgsfieldJobId: '93922d51-8c86-4cde-859b-a793a1d5d254', generatedAt: '2026-07-02', status: 'generated', date: '2026-07-02', day: 'Wed', creator: 'Ava', emoji: '☕', concept: 'NYC morning coffee', overlayText: 'nyc mornings 🗽', prompt: 'Ava NYC apartment window sunrise deep-V cream silk cami revealing cleavage bombshell hair holding coffee mug 9:16.' },
  { id: 'a-jul03', date: '2026-07-03', day: 'Thu', creator: 'Ava', emoji: '🏎️', concept: 'Pink Ferrari drive reveal', overlayText: 'thursday drive 💗', prompt: 'MODEL: nano_banana_2 (need to lock car). CHARACTER FACE LOCK: <<<bf46fc65-6637-4898-b5ac-99e10b772aca>>> (Ava Monroe Reference Element). CAR: custom Rosa Corsa (bright pink) Ferrari 488 GTB with yellow Ferrari calipers + beige nappa leather interior visible through open driver window + polished silver alloys + yellow Ferrari prancing horse badge on hood + New York vanity plate "AVA MNR" clearly visible on front, parked in front of The Plaza Hotel NYC valet stand at 6pm golden hour, gold-trimmed hotel entrance visible behind, other luxury cars softly blurred. WARDROBE: Ava wearing plunging deep-V white bodycon Balmain mini dress REVEALING tasteful cleavage + white pointed Christian Louboutin heels + small white Hermès Kelly clutch + gold layered necklaces + tiny diamond studs + oversized black Celine sunglasses. HAIR: bombshell voluminous platinum-blonde beach waves cascading over shoulders. MAKEUP: soft glam — bronze smoky eye, dewy luminous highlight, glossy nude-pink lip. POSE: leaning back against the front-driver-side fender of the Ferrari, right leg crossed over left, right hand on hood, left holding clutch at hip, chin tilted up sultry, direct sultry gaze at camera with small confident smirk. FACE MARKER: tiny mole on left collarbone (identity lock). LIGHTING: warm golden hour sunset side-light from her left creating dimensional glow on skin, dress, and pink car body. CINEMATOGRAPHY: 9:16 story vertical, phone chest-height capturing full car body + plate + Ava. TEXT OVERLAY: "thursday drive 💗" hand-drawn Instagram Story text at top-third in white script. Hyperrealistic Instagram Story 9:16, real skin pores + car paint reflections, slight film grain, iPhone 17 Pro Max quality. BOLD SEXY editorial luxury bombshell. No CGI, no plastic skin. Lock car face and plate for reuse.' },
  { id: 'a-jul04', date: '2026-07-04', day: 'Fri', creator: 'Ava', emoji: '🇺🇸', concept: '4th of July slip dress', overlayText: 'happy 4th 🇺🇸', prompt: 'Ava NYC Soho street 4th of July deep-V white silk slip dress revealing cleavage + red pointed heels bombshell hair 9:16.' },
  { id: 'a-jul05', date: '2026-07-05', day: 'Sat', creator: 'Ava', emoji: '✨', concept: 'Saturday OOTD mirror', overlayText: 'saturday fit ✨', prompt: 'Ava NYC bedroom mirror deep-V black silk halter bodysuit revealing cleavage + gold necklaces bombshell hair moody light 9:16.' },
  { id: 'a-jul06', date: '2026-07-06', day: 'Sun', creator: 'Ava', emoji: '🛌', concept: 'Lazy Sunday NYC', overlayText: 'nothing today 🥐', prompt: 'Ava NYC apartment cream sofa oversized knit sweater falling off shoulder revealing tasteful cleavage coffee cup morning 9:16.' },
  { id: 'a-jul07', date: '2026-07-07', day: 'Mon', creator: 'Ava', emoji: '💼', concept: 'NYC office chic', overlayText: 'monday boss 💼', prompt: 'Ava NYC office elevator mirror deep-V black satin blouse revealing cleavage + tailored trousers bombshell hair sultry gaze 9:16.' },
  { id: 'a-jul08', date: '2026-07-08', day: 'Tue', creator: 'Ava', emoji: '💻', concept: 'Café work session', overlayText: 'tuesday cafe 💌', prompt: 'Ava at NYC coffee shop window seat MacBook + iced latte deep-V cream ribbed turtleneck revealing cleavage bombshell hair 9:16.' },
  { id: 'a-jul09', date: '2026-07-09', day: 'Wed', creator: 'Ava', emoji: '👗', concept: 'NYC closet flex', overlayText: 'closet closet closet 👗', prompt: 'Ava NYC apartment closet mirror deep-V black silk halter bodysuit revealing cleavage designer bags visible bombshell hair 9:16.' },
  { id: 'a-jul10', date: '2026-07-10', day: 'Thu', creator: 'Ava', emoji: '🐕', concept: 'Marshall Central Park', overlayText: 'thursday with him 🐕', prompt: 'Ava walking Marshall (element lock Golden Retriever) at NYC Central Park autumn morning cream trench coat coffee joyful smile 9:16.' },
  { id: 'a-jul11', date: '2026-07-11', day: 'Fri', creator: 'Ava', emoji: '🍷', concept: 'NYC dinner date', overlayText: 'friday spoiled 🍷', prompt: 'Ava at chic NYC restaurant deep-V black silk mini dress revealing cleavage + gold jewelry cocktail warm moody light 9:16.' },
  { id: 'a-jul12', date: '2026-07-12', day: 'Sat', creator: 'Ava', emoji: '🐕', concept: 'Marshall + coffee walk', overlayText: 'saturday errands 🐕☕', prompt: 'Ava NYC café patio with Marshall (element) beside her deep-V cream silk halter revealing cleavage designer coffee cup bombshell hair 9:16.' },
  { id: 'a-jul13', date: '2026-07-13', day: 'Sun', creator: 'Ava', emoji: '🛌', concept: 'Sunday softness', overlayText: 'sundays are for slow 🥐', prompt: 'Ava NYC bathtub selfie shoulders-up candles bubbles wet blonde hair no makeup dewy 9:16.' },
  { id: 'a-jul14', date: '2026-07-14', day: 'Mon', creator: 'Ava', emoji: '💗', concept: 'Marcus dinner', overlayText: 'monday date 🖤', prompt: 'Ava + Marcus (boyfriend lock Latino-American man in tailored navy Loro Piana suit) at Cipriani NYC Ava in deep-V black silk mini dress revealing cleavage sultry candid 9:16.' },
  { id: 'a-jul15', date: '2026-07-15', day: 'Tue', creator: 'Ava', emoji: '🎒', concept: 'Louis Vuitton packing', overlayText: 'DXB in 24h 🌴', prompt: 'Overhead Ava\'s NYC bedroom bed with LV luggage open bikinis silk dresses gold heels 9:16.', storyArc: 'dubai' },
  { id: 'a-jul16', date: '2026-07-16', day: 'Wed', creator: 'Ava', emoji: '🏨', concept: 'Dubai suite reveal', overlayText: 'suite 4207 🌴', prompt: 'Ava Dubai luxury hotel suite balcony Burj Khalifa view deep-V silk champagne robe revealing cleavage bombshell hair champagne 9:16.', storyArc: 'dubai' },
  { id: 'a-jul17', date: '2026-07-17', day: 'Thu', creator: 'Ava', emoji: '🥂', concept: 'Nobu group toast', overlayText: 'my sisters 🥂', prompt: 'Ava + 4 friends Soul V2 at Nobu Dubai table champagne toast candid laughing bombshell 9:16.', storyArc: 'dubai' },
  { id: 'a-jul18', date: '2026-07-18', day: 'Fri', creator: 'Ava', emoji: '🖤', concept: 'Zuma dinner', overlayText: 'dressed like sin 🖤', prompt: 'Ava at Zuma Dubai deep-V black sequin bodycon dress revealing cleavage bombshell hair Burj Khalifa night backdrop 9:16.', storyArc: 'dubai' },
  { id: 'a-jul19', date: '2026-07-19', day: 'Sat', creator: 'Ava', emoji: '👙', concept: 'Yacht bikini', overlayText: 'yacht life 🛥️', prompt: 'Ava on yacht edge Dubai Marina deep-V white silk crochet bikini top revealing cleavage + white flowy sarong bombshell blonde champagne Palm Jumeirah 9:16.', storyArc: 'dubai' },
  { id: 'a-jul20', date: '2026-07-20', day: 'Sun', creator: 'Ava', emoji: '🥂', concept: 'Dubai brunch mimosas', overlayText: 'brunch >>> 🥂', prompt: 'Ava + 4 friends at Dubai brunch oversized sunglasses mimosas cream silk sets candid laughing 9:16.', storyArc: 'dubai' },
  { id: 'a-jul21', date: '2026-07-21', day: 'Mon', creator: 'Ava', emoji: '💔', concept: 'Emirates business class', overlayText: 'wistful 🌆', prompt: 'Ava selfie in Emirates business class flying back cream loungewear deep-V revealing cleavage iPad polaroid collage 9:16.', storyArc: 'dubai' },
  { id: 'a-jul22', date: '2026-07-22', day: 'Tue', creator: 'Ava', emoji: '🌆', concept: 'NYC skyline back', overlayText: 'home 🗽', prompt: 'Ava NYC apartment window morning post-Dubai sun-kissed deep-V cream slip revealing cleavage bombshell hair coffee 9:16.' },
  { id: 'a-jul23', date: '2026-07-23', day: 'Wed', creator: 'Ava', emoji: '🐕', concept: 'Marshall reunion', overlayText: 'my boy 🐕💛', prompt: 'Ava kneeling reunion Marshall jumping into arms joyful laugh deep-V cream sweater dress revealing cleavage 9:16.' },
  { id: 'a-jul24', date: '2026-07-24', day: 'Thu', creator: 'Ava', emoji: '💼', concept: 'Office chic Thursday', overlayText: 'thursday fits 💼', prompt: 'Ava NYC office elevator mirror deep-V cream blouse revealing cleavage + tailored trousers bombshell hair sultry gaze 9:16.' },
  { id: 'a-jul25', date: '2026-07-25', day: 'Fri', creator: 'Ava', emoji: '🏎️', concept: 'Hamptons drive Ferrari', overlayText: 'hamptons bound 🏎️💗', prompt: 'Ava standing beside her Rosa Corsa pink Ferrari 488 GTB NY plate AVA MNR at Hamptons driveway, cream silk headscarf + deep-V white sundress revealing cleavage + oversized Chanel sunglasses 9:16.', storyArc: 'hamptons' },
  { id: 'a-jul26', date: '2026-07-26', day: 'Sat', creator: 'Ava', emoji: '👙', concept: 'Hamptons bikini pool', overlayText: 'pool day 🌊', prompt: 'Ava at Hamptons luxury pool plunging deep-V nude satin bikini top revealing cleavage + gold body chain bombshell wet blonde hair champagne editorial 9:16.', storyArc: 'hamptons' },
  { id: 'a-jul27', date: '2026-07-27', day: 'Sun', creator: 'Ava', emoji: '☀️', concept: 'Hamptons brunch', overlayText: 'never coming back 🌊', prompt: 'Ava at Hamptons beach brunch table cream silk crochet set revealing collarbones + oysters + rosé wine bombshell hair 9:16.', storyArc: 'hamptons' },
  { id: 'a-jul28', date: '2026-07-28', day: 'Mon', creator: 'Ava', emoji: '🐕', concept: 'Marshall park walk', overlayText: 'monday but marshall 🐕', prompt: 'Ava walking Marshall (element) NYC Central Park morning matching cream trench coffee joyful smile bombshell hair 9:16.' },
  { id: 'a-jul29', date: '2026-07-29', day: 'Tue', creator: 'Ava', emoji: '💼', concept: 'NYC office polish', overlayText: 'city, i love you 🗽', prompt: 'Ava NYC office rooftop skyline view deep-V cream silk blouse revealing cleavage bombshell hair coffee 9:16.' }
]
